--CREATING USER ROLES--
--INSERT INTO authorities (authority) VALUES ('ROLE_ADMIN')
--INSERT INTO authorities (authority) VALUES ('ROLE_USER')
--INSERT INTO authorities (authority) VALUES ('ROLE_DOMAIN')